### ISSUE TITLE
Gatling failed. Simulations compilation failed.

### ISSUE THREAD

**Issue by b3lowster** [gatling/gatling-maven-plugin-demo#11]
Could you help me to figure out. Why do I have such problem?

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building clibrary 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gatling-maven-plugin:2.1.7:execute (default-cli) @ clibrary ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.967s
[INFO] Finished at: Fri Jan 15 00:16:21 EET 2016
[INFO] Final Memory: 8M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.1.7:execute (default-cli) on project clibrary: Gatling failed. Simulations compilation failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

Thanks in advance

**Comment by slandelle** [comment]
For some reason, your simulations failed to compile. As you're the only one to have them, only you can tell.

For questions, please ask our Google Group, not the bug tracker.

**Comment by b3lowster** [comment]
The thing is that plugin works weird. I can get this an error three time but afterwards test is run. Since I decide to create an issue

**Comment by slandelle** [comment]
reproducer please

**Comment by r-alukhanov** [comment]
I had similar behavior, if the plugin was not able to find any simulation to run. In some cases the plugin says than no simulation was found, but in other cases it says nothing. It is weird. :-(

I added following XML to pom.xml to fix it.
        <sourceDirectory>src/main/scala</sourceDirectory>
        <testSourceDirectory>src/test/scala</testSourceDirectory>
